name: 'Dr. Ada, Longevity, Health, Wellbeing'
favicon: null
layout_spectrum: 0.94592
typography_spectrum: 0.65339
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffd500'
    - '#d40000'
    - '#bb6436'
    - '#582d00'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.9460476757958531
purpose: []
